first try

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,6 +1,13 @@
 #!/bin/sh
 
-echo "I'm here !!!"
+# Exit immediately if command returns non-zero status code
+set -e
 
-exec $STI_SCRIPTS_PATH/assemble
+echo "Install nginx configuration files..."
+cp conf.d/sso-proxy.conf $NGINX_CONFIGURATION_PATH/
+
+echo "Creating empty dirs to hold serving certs and trusted CAs..."
+mkdir -p $APP_ROOT/etc/serving-cert/ $APP_ROOT/etc/ca-certs/
+
+exit 0
 
